#!/usr/bin/env bash
# Service health check and diagnostics script
# Usage: bash scripts/health_check.sh [--fix-env] [--start-services]

set -u
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║          EXOMAPS SERVICE HEALTH CHECK                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"

# Function to check port
check_port() {
    local host=$1
    local port=$2
    local timeout=${3:-2}
    
    timeout $timeout bash -c "echo >/dev/tcp/$host/$port" 2>/dev/null && return 0 || return 1
}

# Function to get IP that can reach host
get_reachable_ip() {
    local host=$1
    
    # Try localhost first
    if check_port "127.0.0.1" 5432; then
        echo "127.0.0.1"
        return 0
    fi
    
    # Try actual hostname
    if check_port "localhost" 5432; then
        echo "localhost"
        return 0
    fi
    
    # Try Docker network
    if check_port "db" 5432 2>/dev/null; then
        echo "db"
        return 0
    fi
    
    return 1
}

# Check PostgreSQL
echo -e "\n${BLUE}[1/4] PostgreSQL${NC}"
if check_port "127.0.0.1" 5432; then
    echo -e "${GREEN}✓${NC} PostgreSQL available on 127.0.0.1:5432"
    POSTGRES_HOST="127.0.0.1"
elif check_port "localhost" 5432; then
    echo -e "${GREEN}✓${NC} PostgreSQL available on localhost:5432"
    POSTGRES_HOST="localhost"
elif check_port "db" 5432; then
    echo -e "${GREEN}✓${NC} PostgreSQL available on db:5432 (Docker)"
    POSTGRES_HOST="db"
else
    echo -e "${RED}✗${NC} PostgreSQL not found on any interface"
    echo "   Start with: docker-compose up -d db"
    POSTGRES_HOST=""
fi

# Check Redis
echo -e "\n${BLUE}[2/4] Redis${NC}"
if check_port "127.0.0.1" 6379; then
    echo -e "${GREEN}✓${NC} Redis available on 127.0.0.1:6379"
    REDIS_HOST="127.0.0.1"
elif check_port "redis" 6379; then
    echo -e "${GREEN}✓${NC} Redis available on redis:6379 (Docker)"
    REDIS_HOST="redis"
else
    echo -e "${YELLOW}⚠${NC} Redis not found (optional for caching)"
    REDIS_HOST=""
fi

# Check Flask  
echo -e "\n${BLUE}[3/4] Flask (Web App)${NC}"
if check_port "127.0.0.1" 5000; then
    echo -e "${GREEN}✓${NC} Flask available on 127.0.0.1:5000"
    FLASK_HOST="127.0.0.1"
else
    echo -e "${YELLOW}⚠${NC} Flask not running (start with: python src/app/app.py)"
    FLASK_HOST=""
fi

# Check Docker Compose
echo -e "\n${BLUE}[4/4] Docker Services${NC}"
if command -v docker-compose &> /dev/null; then
    echo -e "${GREEN}✓${NC} docker-compose available"
    
    # Count running services
    RUNNING=$(docker-compose -f "$ROOT_DIR/docker-compose.yml" ps -q 2>/dev/null | wc -l)
    echo "   Running containers: $RUNNING"
else
    echo -e "${YELLOW}⚠${NC} docker-compose not found"
fi

# Summary
echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SUMMARY${NC}"

if [ -n "$POSTGRES_HOST" ]; then
    echo -e "${GREEN}✓${NC} Database connectivity:  OK (host: $POSTGRES_HOST)"
else
    echo -e "${RED}✗${NC} Database connectivity:  FAILED"
fi

if [ -n "$REDIS_HOST" ]; then
    echo -e "${GREEN}✓${NC} Cache connectivity:     OK (host: $REDIS_HOST)"
else
    echo -e "${YELLOW}⚠${NC} Cache connectivity:     Not available"
fi

if [ -n "$FLASK_HOST" ]; then
    echo -e "${GREEN}✓${NC} Web app connectivity:   OK (host: $FLASK_HOST)"
else
    echo -e "${YELLOW}⚠${NC} Web app connectivity:   Not running"
fi

# Generate environment file
if [ "${1:-}" = "--fix-env" ] || [ "${2:-}" = "--fix-env" ]; then
    echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ WRITING ENV${NC}"
    
    cat > "$ROOT_DIR/.env.auto" <<EOF
# Auto-generated by health_check.sh - $(date)
POSTGRES_USER=postgres
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-}
POSTGRES_DB=exomaps
POSTGRES_HOST=${POSTGRES_HOST:-127.0.0.1}
POSTGRES_PORT=5432
APPUSER=appuser
APPPASS=${APPPASS:-}
REDIS_HOST=${REDIS_HOST:-}
REDIS_PORT=6379
FLASK_HOST=${FLASK_HOST:-127.0.0.1}
FLASK_PORT=5000
EOF
    
    echo -e "${GREEN}✓${NC} Written to .env.auto"
    echo "   Use with: export \$(cat .env.auto | xargs)"
fi

# Start services if requested
if [ "${1:-}" = "--start-services" ] || [ "${2:-}" = "--start-services" ]; then
    echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ STARTING SERVICES${NC}"
    
    if [ -z "$POSTGRES_HOST" ]; then
        echo "Starting PostgreSQL..."
        docker-compose -f "$ROOT_DIR/docker-compose.yml" up -d db
        sleep 5
    fi
    
    if [ -z "$REDIS_HOST" ]; then
        echo "Starting Redis..."
        docker-compose -f "$ROOT_DIR/docker-compose.yml" up -d redis
        sleep 2
    fi
    
    echo -e "\n${GREEN}✓${NC} Services started"
    echo "   Run again to verify: bash scripts/health_check.sh"
fi

# Exit code
if [ -n "$POSTGRES_HOST" ]; then
    exit 0
else
    exit 1
fi
