#!/usr/bin/env bash
# Universal setup script - handles all environment and service setup
# Usage: bash scripts/setup.sh [--docker] [--local] [--all]

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SETUP_MODE="${1:-auto}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}╔════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║         EXOMAPS UNIVERSAL SETUP SCRIPT                     ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════╝${NC}"

# Step 1: Create .db_env if missing
echo -e "\n${BLUE}[1/4] Checking environment configuration${NC}"
if [ ! -f "$ROOT_DIR/dbs/.db_env" ]; then
    echo "Creating dbs/.db_env from .env.example..."
    cat > "$ROOT_DIR/dbs/.db_env" <<EOF
POSTGRES_USER=postgres
POSTGRES_PASSWORD=
POSTGRES_DB=exomaps
APPUSER=appuser
APPPASS=
EOF
    echo -e "${YELLOW}⚠ Edit dbs/.db_env and set POSTGRES_PASSWORD and APPPASS${NC}"
fi

if [ ! -f "$ROOT_DIR/.env" ]; then
    if [ -f "$ROOT_DIR/.env.example" ]; then
        echo "Copying .env.example → .env  (edit to add passwords)"
        cp "$ROOT_DIR/.env.example" "$ROOT_DIR/.env"
    else
        echo "Creating .env..."
        cat > "$ROOT_DIR/.env" <<EOF
# Environment configuration - auto-generated by setup.sh
# Fill in POSTGRES_PASSWORD and APPPASS before running.

POSTGRES_USER=postgres
POSTGRES_PASSWORD=
POSTGRES_DB=exomaps
POSTGRES_HOST=127.0.0.1
POSTGRES_PORT=5432
APPUSER=appuser
APPPASS=
REDIS_HOST=127.0.0.1
REDIS_PORT=6379
FLASK_HOST=127.0.0.1
FLASK_PORT=5000
EOF
    fi
    echo -e "${YELLOW}⚠ Edit .env and set POSTGRES_PASSWORD and APPPASS before proceeding${NC}"
fi

# Step 2: Install Python dependencies
echo -e "\n${BLUE}[2/4] Installing Python dependencies${NC}"
if [ -f "$ROOT_DIR/dbs/requirements-lock.txt" ]; then
    echo "Using locked requirements..."
    pip install -q -r "$ROOT_DIR/dbs/requirements-lock.txt" || true
    pip install -q -r "$ROOT_DIR/src/requirements-lock.txt" || true
else
    echo "Using unpinned requirements..."
    pip install -q -r "$ROOT_DIR/dbs/requirements.txt" || true
    pip install -q -r "$ROOT_DIR/src/requirements.txt" || true
fi
echo -e "${GREEN}✓${NC} Dependencies installed"

# Step 3: Run health check and auto-detect services
echo -e "\n${BLUE}[3/4] Detecting available services${NC}"
bash "$ROOT_DIR/scripts/health_check.sh" --fix-env || true

# Step 4: Start Docker services if needed
echo -e "\n${BLUE}[4/4] Service startup (mode: $SETUP_MODE)${NC}"

if [ "$SETUP_MODE" = "docker" ] || [ "$SETUP_MODE" = "all" ]; then
    echo "Starting Docker services..."
    
    if ! command -v docker-compose &> /dev/null; then
        echo -e "${RED}✗${NC} docker-compose not found"
    else
        cd "$ROOT_DIR"
        
        # Stop old containers if any
        docker-compose down 2>/dev/null || true
        sleep 2
        
        # Start fresh
        echo "  - Starting PostgreSQL..."
        docker-compose up -d db redis || true
        
        echo "  - Waiting for services to be healthy..."
        for i in {1..30}; do
            if bash "$ROOT_DIR/scripts/health_check.sh" >/dev/null 2>&1; then
                echo -e "${GREEN}✓${NC} Services ready"
                break
            fi
            sleep 1
            echo -n "."
        done
    fi
fi

# Step 5: Apply migrations if database is available
echo -e "\n${BLUE}[5/5] Database initialization${NC}"
if python3 -c "from dbs.service_discovery import ServiceDiscovery; sd = ServiceDiscovery(verbose=False); exit(0 if sd.services['postgres'].status.value == 'available' else 1)" 2>/dev/null; then
    echo "Initializing database schemas..."
    python3 "$ROOT_DIR/dbs/database.py" || true
    echo -e "${GREEN}✓${NC} Database ready"
else
    echo -e "${YELLOW}⚠${NC} Database not yet available (will try on next run)"
fi

# Final status
echo -e "\n${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ NEXT STEPS${NC}"
echo ""
echo "1. Verify services are running:"
echo "   bash scripts/health_check.sh"
echo ""
echo "2. Load environment variables:"
echo "   export \$(cat .env.auto | xargs)"
echo ""
echo "3. Start Flask development server:"
echo "   python src/app/app.py"
echo ""
echo "4. Or run a specific phase:"
echo "   bash scripts/run_phase01_pipeline.sh"
echo "   bash scripts/run_phase04_pipeline.sh"
echo ""
echo -e "${GREEN}✓${NC} Setup complete!"
